[build]
builder = "dockerfile"
# Force fresh build - updated 2025-01-12 - fixing frontend serving

[deploy]
startCommand = "python working_app.py"
healthcheckPath = "/api/ping"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
