[build]
builder = "dockerfile"

[deploy]
startCommand = "python -m uvicorn backend.api.main:app --host 0.0.0.0 --port 8000"
healthcheckPath = "/api/ping"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
