"""Add lead scoring fields

Revision ID: 474aa80a0e1b
Revises: 40103f24b07e
Create Date: 2025-07-27 18:24:58.213842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '474aa80a0e1b'
down_revision: Union[str, Sequence[str], None] = '40103f24b07e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('score', sa.Integer(), nullable=True))
    op.add_column('leads', sa.Column('score_updated_at', sa.DateTime(), nullable=True))
    op.add_column('leads', sa.Column('score_factors', sa.String(), nullable=True))
    op.add_column('leads', sa.Column('score_confidence', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'score_confidence')
    op.drop_column('leads', 'score_factors')
    op.drop_column('leads', 'score_updated_at')
    op.drop_column('leads', 'score')
    # ### end Alembic commands ###
