"""add_organization_id_to_deals

Revision ID: 9de8f04735f7
Revises: 7bdc78fccad6
Create Date: 2025-09-13 17:59:53.921200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9de8f04735f7'
down_revision: Union[str, Sequence[str], None] = '7bdc78fccad6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add organization_id column as nullable first
    op.add_column('deals', sa.Column('organization_id', sa.Integer(), nullable=True))
    
    # Update existing deals to use default organization (ID 1)
    op.execute("UPDATE deals SET organization_id = 1 WHERE organization_id IS NULL")
    
    # Now make the column NOT NULL
    op.alter_column('deals', 'organization_id', nullable=False)
    
    # Add foreign key constraint
    op.create_foreign_key('fk_deals_organization', 'deals', 'organizations', ['organization_id'], ['id'])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deals', type_='foreignkey')
    op.drop_column('deals', 'organization_id')
    # ### end Alembic commands ###
