"""Add customer accounts and post-sale workflow fields

Revision ID: c3afba0ee0d1
Revises: 000913814147
Create Date: 2025-09-18 03:39:20.968490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3afba0ee0d1'
down_revision: Union[str, Sequence[str], None] = '000913814147'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('account_name', sa.String(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('account_type', sa.String(), nullable=True),
    sa.Column('onboarding_status', sa.String(), nullable=True),
    sa.Column('success_manager_id', sa.Integer(), nullable=True),
    sa.Column('health_score', sa.Float(), nullable=True),
    sa.Column('engagement_level', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['success_manager_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('deals', sa.Column('status', sa.String(), nullable=True))
    op.add_column('deals', sa.Column('outcome_reason', sa.String(), nullable=True))
    op.add_column('deals', sa.Column('customer_account_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'deals', 'customer_accounts', ['customer_account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deals', type_='foreignkey')
    op.drop_column('deals', 'customer_account_id')
    op.drop_column('deals', 'outcome_reason')
    op.drop_column('deals', 'status')
    op.drop_table('customer_accounts')
    # ### end Alembic commands ###
